# Generated by Django 2.2.1 on 2019-07-05 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='发布时间',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articles',
            name='文章摘要',
            field=models.TextField(default='无摘要'),
        ),
    ]
